### PR TITLE
Bump kittens version; add Traverse derivation

### PR DESCRIPTION
**Pull request by oleg-py**
New version of Kittens has Traverse derivation, so why not have it in catnip? :)

### CODE REVIEW

**Comment by MateuszKubuszok** [comment]
@oleg-py Anything else appeared? :)

**Comment by MateuszKubuszok** [comment]
Merged! Thanks! :)

**Comment by oleg-py** [comment]
@MateuszKubuszok there are derivations for `Pure` and `EmptyK` (IIRC), but I failed to make them work in a reasonable time, so I went with just Traverse for this PR :)

**Comment by MateuszKubuszok** [comment]
Ok, Well figure something out later :)

**Pull request merged**
